export const CONNECT_USER_START = 'CONNECT_USER_START';
export const CONNECT_USER_SUCCESS = 'CONNECT_USER_SUCCESS';
export const CONNECT_USER_ERROR = 'CONNECT_USER_ERROR';

export const FIGHT_START = 'FIGHT_START';
export const FIGHT_SUCCESS = 'FIGHT_SUCCESS';
export const FIGHT_ERROR = 'FIGHT_ERROR';

